### ISSUE TITLE
material_test files

### ISSUE THREAD

**Issue by philliptee** [shocker-0x15/VLR#2]
Hi,
I've finally got your project to compile and I am now unable to run it because I am missing the file called "jumping_colors.png" which is suppose to be inside resources/material_test/.

I've found the other missing files ( mitsuba_knob.obj and Chelsea_Stairs_3k.hdr) from googling for the filenames but I think "jumping_colors.png" is too ambiguous and I can't find it. Can you direct me to where I can find this file?

**Comment by shocker-0x15** [comment]
Thank you for interest in my renderer.
That image is a test pattern made by myself for comparing color interpolation difference between RGB and spectral rendering.
I pushed the image "jumping_colors.png" just now.

Many of other models/images are obtained from following sites:
https://casual-effects.com/data/
http://www.hdrlabs.com/sibl/archive.html

**Comment by philliptee** [comment]
Thanks but I still can't get the default MaterialTestScene to work because of the mitsuba knob obj file (that I got from morgan mcguire's resource page) is not being read properly??

Anyways, I have figured out that the rendered scene is changed by commenting in/out lines in scene.cpp. I have successfully been able to render other scenes with obj files.. I will close this issue because it doesn't seem like a problem with your project.
